title: "Hello standard!"
lang: "nl"
url: "https://jouw-website.html"
logo: "/assets/img/logo.png"
logo-alt: Hello Logo
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
