title: " "
lang: "nl"
url: "https://jouw-website.html"
logo: "/assets/img/logo.svg"
logo-alt: " "
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
