title: "HelloWorld"
lang: "nl"
url: "https://mywebsite.nl"
logo: "/assets/img/logo.svg"
logo-alt: " "
google_site_verification:      #search console


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      _comments:
        title: Paginatitel voor in Google (maximaal 60 tekens minus het aantal tekens in de bedrijfsnaam)
        description: Paginabeschrijving voor in Google/SEO (50-160 tekens)
        alt: Beschrijving van de afbeelding - max 10 woorden

_explore:
  groups:
    - heading: Pagina's
      collections:
        - pages

uploads_dir: "/assets/img/uploads/:title"

picture:
  output: "assets/img/picture-generated"
  ignore_missing_images: true
  fast_build: [development]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# collections:
#   collection1:
#     output: false
#     _hide_content: true
#   collection2:
#     output: false
#     _hide_content: true

picture:
  output: "assets/img/picture-generated"
  ignore_missing_images: development
  fast_build: [development]
  suppress_warnings: true
  # disabled: development

# Cloudcannon
uploads_dir: "/assets/img/uploads/:title"
_explore:
  groups:
    - heading: Pagina's
      collections:
        - pages
    - heading: Inhoud
      collections:
        - collections
